debian-devkitpro: open source game consoles devkit
Debian containers providing toolchains to create games and
homebrews.

Currently, CI has been disabled due to an issue that occurs when
containers are built by CircleCI:
error: failed retrieving file 'dkp-linux.db' from pkg.devkitpro.org : The requested URL returned error: 403
error: failed retrieving file 'dkp-libs.db' from pkg.devkitpro.org : The requested URL returned error: 403
error: failed to synchronize all databases (failed to retrieve some files)

Signed-off-by: Thomas Perrot <thomas.perrot@tupi.fr>